# Generated by Django 5.1.2 on 2024-10-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cateringservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringorder',
            name='event',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('birthday', 'Birthday Party'), ('private', 'Private Party'), ('other', 'Other')], default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cateringorder',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
